"""add image into genres

Revision ID: 011dd3c7da1d
Revises: f8f8a1146fed
Create Date: 2026-05-29 19:04:54.469881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011dd3c7da1d'
down_revision: Union[str, None] = 'f8f8a1146fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('image_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genres', 'image_url')
    # ### end Alembic commands ###
