"""add plays to tracks

Revision ID: 89c47735db0d
Revises: 0d9f616a6cf3
Create Date: 2026-03-11 15:05:14.206188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c47735db0d'
down_revision: Union[str, None] = '0d9f616a6cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('plays', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'plays')
    # ### end Alembic commands ###
