"""add is_exclusive_sold to track

Revision ID: 8c694e12a990
Revises: f256903b6536
Create Date: 2026-05-06 11:52:07.951407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c694e12a990'
down_revision: Union[str, None] = 'f256903b6536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('is_exclusive_sold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'is_exclusive_sold')
    # ### end Alembic commands ###
