"""add bpm field into tracks

Revision ID: 8e76958dc434
Revises: 836bedd60dbc
Create Date: 2026-03-13 18:56:42.793747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e76958dc434'
down_revision: Union[str, None] = '836bedd60dbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('bpm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'bpm')
    # ### end Alembic commands ###
