"""fix relantioship users and author

Revision ID: cd4959ac5ccd
Revises: bbcdf993ef88
Create Date: 2026-03-28 19:24:33.061826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4959ac5ccd'
down_revision: Union[str, None] = 'bbcdf993ef88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'authors', ['user_id'])
    op.create_foreign_key(None, 'authors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_column('authors', 'user_id')
    # ### end Alembic commands ###
