"""add license into purchase

Revision ID: f256903b6536
Revises: cd4959ac5ccd
Create Date: 2026-03-30 09:34:57.253829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f256903b6536'
down_revision: Union[str, None] = 'cd4959ac5ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE licensetype AS ENUM ('standard', 'extended', 'exclusive')")
    op.add_column('purchases', sa.Column('license_type', sa.Enum('standard', 'extended', 'exclusive', name='licensetype'), nullable=False))
    op.add_column('purchases', sa.Column('comment', sa.Text(), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'is_exclusive')
    op.drop_column('purchases', 'comment')
    op.drop_column('purchases', 'license_type')
    # ### end Alembic commands ###
